name: CI

on:
  push: {}
  pull_request: {}

permissions:
  contents: write

jobs:
  tests-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest-qt
      - name: Run tests
        run: pytest -q
      - name: Build application (non-interactive)
        shell: powershell
        run: |
          python -u build_complete_solution.py
      - name: Upload portable artifact
        uses: actions/upload-artifact@v4
        with:
          name: portable-zip
          path: VideoDownloader_Portable_v1.0.0.zip
      - name: Commit portable artifact back to branch
        shell: powershell
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add VideoDownloader_Portable_v1.0.0.zip || Write-Output "No artifact to add"
          if (git status --porcelain) { git commit -m "ci: add portable build artifact" } else { Write-Output "No changes to commit" }
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
